### PR TITLE
kindly check and approve.

### PR DESCRIPTION
**Pull request by eeluwole1**
Made a final check

### CODE REVIEW

**Review by cbugtai — APPROVED** [review]

**Review by cbugtai — CHANGES_REQUESTED** [review]
need to mock localStorage for the tests

**Comment by eeluwole1** [comment]
Kindly check and approve

**Review by cbugtai — APPROVED** [review]

**Comment by eeluwole1** [comment]
Kindly check again

**Comment by eeluwole1** [comment]
kindly check for approval

**Pull request merged**
